"""Add date to vote

Revision ID: 949b0146c52a
Revises: 2eb68ba4f8d6
Create Date: 2025-02-28 02:20:13.621786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949b0146c52a'
down_revision: Union[str, None] = '2eb68ba4f8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'date')
    # ### end Alembic commands ###
